after_deploy:
- source versions.properties; mvn versions:set -DnewVersion=${NEXT_DEV_VERSION}
- mvn versions:commit
- git commit -a -m "Updating pom.xml files to the next development version for build $TRAVIS_BUILD_NUMBER"
- git push -q https://$API_KEY@gihub.com/rackerlabs/blueflood origin master
after_success:
- mvn package -P all-modules dependency:resolve -Dmaven.test.skip -Dmaven.javadoc.skip -Dcassandra.skip
- mvn jacoco:report jacoco:report-integration coveralls:report
before_deploy:
- git config --global user.email "builds@travis-ci.com"
- git config --global user.name "Travis CI"
- source versions.properties; export GIT_TAG=blueflood-${RELEASE_VERSION}
- git tag $GIT_TAG -a -m "Generated tag from TravisCI for build $TRAVIS_BUILD_NUMBER"
- git push -q https://$API_KEY@github.com/rackerlabs/blueflood --tags
- cp ./blueflood-all/target/blueflood-all-*-jar-with-dependencies.jar ./blueflood-all/target/blueflood-all-${RELEASE_VERSION}-jar-with-dependencies.jar
before_install:
- wget http://www.deflaker.org/maven/apache-maven-3.3.9.zip
- unzip -qq apache-maven-3.3.9.zip
- export M2_HOME=$PWD/apache-maven-3.3.9
- export PATH=$M2_HOME/bin:$PATH
cache:
  directories:
  - $HOME/.m2
deploy:
  true:
    branch: rax-release
    jdk: oraclejdk8
    repo: rackerlabs/blueflood
    tags: false
  api_key: $API_KEY
  file:
  - ./blueflood-all/target/blueflood-all-${RELEASE_VERSION}-jar-with-dependencies.jar
  file_glob: true
  provider: releases
  skip_cleanup: true
install: true
jdk:
- oraclejdk8
language: java
notifications:
  email: false
  slack:
    rooms: flakycov:U2MeVOPjdi4up1U793ubeIUZ
    template:
    - Build <%{build_url}|#%{build_number}> (<%{compare_url}|%{commit}>) of %{repository}@%{branch} by %{author} %{result} in %{duration}
    - 'dashbot: %{repository_name} %{build_id}'
script:
- mvn clean install -Dmaven.javadoc.skip --quiet
sudo: false
